apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  labels:
    app: keycloak-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: ${image}
        env:
        - name: KC_HOSTNAME
          value: aws-keycloak.songshu.ca
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin123"
        - name: DB_VENDOR
          value: "mysql"
        - name: DB_ADDR
          value: "10.255.255.138"
        - name: DB_PORT
          value: "3306"
        - name: "DB_DATABASE"
          value: "keycloak-justauth"
        - name: DB_USER
          value: "nprod"
        - name: DB_PASSWORD
          value: "OttRdsNprod2022!#%"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
     kubernetes.io/ingress.class: nginx
  labels:
     app.songshu.ca/name: test
spec:
  tls:
    - hosts:
      - aws-keycloak.songshu.ca
      secretName: songshu-ca-20221017
  rules:
  - host: aws-keycloak.songshu.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-service
            port:
              number: 8080